### ISSUE TITLE
Can't generate experimental HTTPRoute with Gateway API v1.3.0

### ISSUE THREAD

**Issue by shaneutt** [kube-rs/gateway-api-rs#144]
While updating `gateway-api-rs` for [Gateway API v1.3.0](https://github.com/kubernetes-sigs/gateway-api/releases/tag/v1.3.0), I found that the experimental version of `HTTPRoute` can not be generated:

```console
Error: not handling non-string/int enum outside oneOf block
```

With CORS support in Gateway API, a new field called [TrueField](https://github.com/kubernetes-sigs/gateway-api/blob/d7b4030b2e536d900460c7d73ed291288429e3fb/apis/v1/shared_types.go#L770) was added:

```golang
// TrueField is a boolean value that can only be set to true
//
// +kubebuilder:validation:Enum=true
type TrueField bool
```

This is used here:

```golang
	// AllowCredentials indicates whether the actual cross-origin request allows
	// to include credentials.
	//
	// The only valid value for the `Access-Control-Allow-Credentials` response
	// header is true (case-sensitive).
	//
	// If the credentials are not allowed in cross-origin requests, the gateway
	// will omit the header `Access-Control-Allow-Credentials` entirely rather
	// than setting its value to false.
	//
	// Support: Extended
	//
	// +optional
	AllowCredentials TrueField `json:"allowCredentials,omitempty"`
```

This `TrueField` results in an enum which ultimately `kopium` doesn't currently handle:

```yaml
properties:
  cors:
    description: |-
      CORS defines a schema for a filter that responds to the
      cross-origin request based on HTTP response header.

      Support: Extended
    properties:
      allowCredentials:
        description: |-
          AllowCredentials indicates whether the actual cross-origin request allows
          to include credentials.
          The only valid value for the `Access-Control-Allow-Credentials` response
          header is true (case-sensitive).
          If the credentials are not allowed in cross-origin requests, the gateway
          will omit the header `Access-Control-Allow-Credentials` entirely rather
          than setting its value to false.

          Support: Extended
        enum:
        - true
        type: boolean
```

**Comment by shaneutt** [comment]
@clux this one doesn't need action on your part, but I thought you mind find it interesting. 😂 

I can work around the issue with the following patch:

```diff
diff --git a/src/analyzer.rs b/src/analyzer.rs
index b379320..e2ca0ca 100644
--- a/src/analyzer.rs
+++ b/src/analyzer.rs
@@ -206,6 +206,7 @@ fn analyze_enum_properties(
                 }
                 val.to_string()
             }
+            serde_json::Value::Bool(boolean) => boolean.to_string(),
             _ => bail!("not handling non-string/int enum outside oneOf block"),
         };
         let rust_type = "".to_string();
```

That will get `kopium` generation to "work" and emit:

```rust
/// AllowCredentials indicates whether the actual cross-origin request allows
/// to include credentials.
///
/// The only valid value for the `Access-Control-Allow-Credentials` response
/// header is true (case-sensitive).
///
/// If the credentials are not allowed in cross-origin requests, the gateway
/// will omit the header `Access-Control-Allow-Credentials` entirely rather
/// than setting its value to false.
///
/// Support: Extended
#[serde(
    default,
    skip_serializing_if = "Option::is_none",
    rename = "allowCredentials"
)]
pub allow_credentials: Option<bool>,
```

and

```rust
/// CORS defines a schema for a filter that responds to the
/// cross-origin request based on HTTP response header.
///
/// Support: Extended
#[derive(Serialize, Deserialize, Clone, Debug, JsonSchema, PartialEq)]
pub enum HTTPRouteRulesBackendRefsFiltersCorsAllowCredentials {
    #[serde(rename = "true")]
    True,
}
```

Which kind of works, but isn't _quite right_ as ideally the type would be emitted as `Option<HTTPRouteRulesBackendRefsFiltersCorsAllowCredentials>` instead of `Option<bool>`? 🤔 

That said, I'm not just considering what it would take to make this work in `kopium`, but I'm also considering changing it in Gateway API itself: the OpenAPI spec including:

```yaml
        enum:
        - true
        type: boolean
```

Is odd if nothing else. The reason it is that way is because the header it represents works the same way and only allows "true" or not being set at all, so it that's how we got here but I'm considering whether it may be better to simply make that a string "true" in an enum instead.
